targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/**/models/*.dart
        options:
          checked: true
      source_gen:combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
