name: dvm
description: A simple CLI to manage Dart SDK versions.
version: 1.0.0
repository: https://github.com/blendfactory/dvm

environment:
  sdk: ^3.2.3

dependencies:
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.24.0
  yumemi_lints: ^1.2.0
