name: dvmx
description: "Dart Version Management: A simple CLI to manage Dart SDK versions per project."
version: 0.0.3
repository: https://github.com/blendfactory/dvm

executables:
  dvm: dvm

environment:
  sdk: ^3.3.0

dependencies:
  archive: ^3.4.10
  args: ^2.4.2
  collection: ^1.18.0
  file: ^7.0.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.12
  meta: ^1.12.0
  pub_semver: ^2.1.4
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  cli_pkg: ^2.7.2
  crypto: ^3.0.3
  custom_lint: ^0.5.7
  grinder: ^0.9.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.24.0
  yumemi_lints: ^1.2.0
