name: dvm
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
  yumemi_lints: ^1.2.0
