name: dvm
description: A simple CLI to manage Dart SDK versions.
version: 1.0.0
repository: https://github.com/blendfactory/dvm

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
  yumemi_lints: ^1.2.0
