name: dvmx
description: "Dart Version Management: A simple CLI to manage Dart SDK versions per project."
version: 0.0.8+1
repository: https://github.com/blendfactory/dvm

executables:
  dvm: dvm

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^3.6.1
  args: ^2.5.0
  cli_info: ^1.0.0
  collection: ^1.19.0
  file: ^6.1.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  mason_logger: ^0.2.16
  meta: ^1.15.0
  pub_semver: ^2.1.4
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  win32: ^5.5.3

dev_dependencies:
  analyzer: ">=6.0.0 <6.6.0"
  build_runner: ^2.4.12
  cli_info_builder: ^1.0.1
  cli_pkg: ^2.9.0
  crypto: ^3.0.3
  custom_lint: ^0.5.11
  grinder: ^0.9.5
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.8
  test: ^1.25.8
  yumemi_lints: ^2.1.0
