name: dvmx
description: "Dart Version Management: A simple CLI to manage Dart SDK versions per project."
version: 0.0.7
repository: https://github.com/blendfactory/dvm

executables:
  dvm: dvm

environment:
  sdk: ^3.3.0

dependencies:
  archive: ^3.4.10
  args: ^2.4.2
  cli_info: ^1.0.0
  collection: ^1.18.0
  file: ^7.0.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  mason_logger: ^0.2.12
  meta: ^1.12.0
  pub_semver: ^2.1.4
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4

dev_dependencies:
  build_runner: ^2.4.8
  cli_info_builder: ^1.0.1
  cli_pkg: ^2.9.0
  crypto: ^3.0.3
  custom_lint: ^0.5.11
  grinder: ^0.9.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.8
  test: ^1.25.2
  yumemi_lints: ^1.7.0
