name: dvm
description: A simple CLI to manage Dart SDK versions.
version: 0.0.1
repository: https://github.com/blendfactory/dvm

executables:
  dvm:

environment:
  sdk: ^3.2.3

dependencies:
  archive: ^3.4.10
  args: ^2.4.2
  cli_util: ^0.4.1
  collection: ^1.18.0
  file: ^7.0.0
  http: ^1.1.2
  json_annotation: ^4.8.1
  meta: ^1.11.0
  pub_semver: ^2.1.4
  riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  test: ^1.24.0
  yumemi_lints: ^1.2.0
