name: Push Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

permissions:
  contents: write

jobs:
  push-tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Version
        id: extract-version
        run: .github/scripts/extract-version.sh
      - name: Push Tag
        run: .github/scripts/push-tag.sh
        env:
          VERSION: ${{ steps.extract-version.outputs.version }}
