name: Push Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

permissions:
  contents: write

jobs:
  push-tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        uses: actions/create-github-app-token@c8f55efbd427e7465d6da1106e7979bc8aaee856 # v1.10.1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID_BLENDFACTORY_TAG_PUSHER }}
          private-key: ${{ secrets.PRIVATE_KEY_BLENDFACTORY_TAG_PUSHER }}
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Extract Version
        id: extract-version
        run: .github/scripts/extract-version.sh
      - name: Push Tag
        run: .github/scripts/push-tag.sh
        env:
          VERSION: ${{ steps.extract-version.outputs.version }}
