name: Push Tag

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

permissions:
  contents: write

jobs:
  push-tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract Version
        id: extract-version
        run: .github/scripts/extract-version.sh
      - name: Generate App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID_BLENDFACTORY_TAG_PUSHER }}
          private-key: ${{ secrets.PRIVATE_KEY_BLENDFACTORY_TAG_PUSHER }}
      - name: Commit Tag
        run: |
          git config --global user.email "32213113+blendthink@users.noreply.github.com"
          git config --global user.name "blendthink"
          git tag -a ${{ steps.extract-version.outputs.version }} -m "Release ${{ steps.extract-version.outputs.version }}"
      - name: Push Tag
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df # v0.8.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
