name: Release to GitHub and Homebrew

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  # Required for GitHub releases using ginder tasks.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Create a GitHub release
        run: dart run grinder pkg-github-release
  upload-excutables-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-linux
      - name: Build checksums
        run: dart run grinder pkg-checksum-linux
      - name: Extract DVM version
        id: extract-dvm-version
        uses: ./.github/actions/extract-dvm-version
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ steps.extract-dvm-version.outputs.version }}-linux-ia32.sha256
            build/dvm-${{ steps.extract-dvm-version.outputs.version }}-linux-x64.sha256
            build/dvm-${{ steps.extract-dvm-version.outputs.version }}-linux-arm.sha256
            build/dvm-${{ steps.extract-dvm-version.outputs.version }}-linux-arm64.sha256
          tag_name: ${{ steps.extract-dvm-version.outputs.version }}
  upload-excutables-macos:
    needs: create-release
    strategy:
      matrix:
        args:
          [
            { image: macos-latest, arch: x64 },
            { image: macos-latest-xlarge, arch: arm64 },
          ]
    runs-on: ${{ matrix.args.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-macos-${{ matrix.args.arch }}
      - name: Build checksums
        run: dart run grinder pkg-checksum-macos-${{ matrix.args.arch }}
      - name: Extract DVM version
        id: extract-dvm-version
        uses: ./.github/actions/extract-dvm-version
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ steps.extract-dvm-version.outputs.version }}-macos-${{ matrix.args.arch }}.sha256
          tag_name: ${{ steps.extract-dvm-version.outputs.version }}
  upload-excutables-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-windows
      - name: Build checksums
        run: dart run grinder pkg-checksum-windows
      - name: Extract DVM version
        id: extract-dvm-version
        uses: ./.github/actions/extract-dvm-version
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ steps.extract-dvm-version.outputs.version }}-windows-ia32.sha256
            build/dvm-${{ steps.extract-dvm-version.outputs.version }}-windows-x64.sha256
          tag_name: ${{ steps.extract-dvm-version.outputs.version }}
  update-homebrew:
    needs:
      [
        create-release,
        upload-excutables-linux,
        upload-excutables-macos,
        upload-excutables-windows,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup
        uses: ./.github/actions/setup
      - name: Extract DVM version
        id: extract-dvm-version
        uses: ./.github/actions/extract-dvm-version
      - name: Download checksums
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ steps.extract-dvm-version.outputs.version }}
          fileName: "*.sha256"
      - name: Extract checksums
        id: checksums
        shell: bash
        run: |
          echo "sha256_macos_x64=$(cat dvm-${{ steps.extract-dvm-version.outputs.version }}-macos-x64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "sha256_macos_arm64=$(cat dvm-${{ steps.extract-dvm-version.outputs.version }}-macos-arm64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "sha256_linux_x64=$(cat dvm-${{ steps.extract-dvm-version.outputs.version }}-linux-x64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@f4c6bf6752984b3a29fcc135a5e70eb792c40c6b # v1.8.0
        with:
          app-id: ${{ secrets.APP_ID_BLENDFACTORY_REPOSITORY_DISPATCHER }}
          private-key: ${{ secrets.PRIVATE_KEY_BLENDFACTORY_REPOSITORY_DISPATCHER }}
          owner: ${{ github.repository_owner }}
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: blendfactory/homebrew-tap
          event-type: update-dvm
          client-payload: |-
            {
              "version": "${{ steps.extract-dvm-version.outputs.version }}",
              "sha256_macos_x64": "${{ steps.checksums.outputs.sha256_macos_x64 }}",
              "sha256_macos_arm64": "${{ steps.checksums.outputs.sha256_macos_arm64 }}",
              "sha256_linux_x64": "${{ steps.checksums.outputs.sha256_linux_x64 }}"
            }
