name: Release to GitHub

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Create a GitHub release
        run: dart run grinder pkg-github-release
  upload-excutables:
    needs: create-release
    strategy:
      matrix:
        args:
          [
            { image: ubuntu-latest, os: linux },
            { image: macos-latest, os: macos },
            { image: windows-latest, os: windows },
          ]
    runs-on: ${{ matrix.args.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-${{ matrix.args.os }}
      - name: Build checksums
        run: dart run grinder pkg-checksum-${{ matrix.args.os }}
      - name: Extract version on non-Windows
        if: matrix.args.os != 'windows'
        run: echo "version=$(dart run grinder pkg-version)" >> $GITHUB_ENV
      - name: Extract version on Windows
        if: matrix.args.os == 'windows'
        run: |
          "version=$(dart run grinder pkg-version)" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Upload Linux checksums to GitHub
        if: matrix.args.os == 'linux'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-linux-i32.sha256
            build/dvm-${{ env.version }}-linux-x64.sha256
            build/dvm-${{ env.version }}-linux-arm.sha256
            build/dvm-${{ env.version }}-linux-arm64.sha256
          tag_name: ${{ env.version }}
      - name: Upload macOS checksums to GitHub
        if: matrix.args.os == 'macos'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-macos-x64.sha256
            build/dvm-${{ env.version }}-macos-arm64.sha256
          tag_name: ${{ env.version }}
      - name: Upload Windows checksums to GitHub
        if: matrix.args.os == 'windows'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-"$env:version"-windows-i32.sha256
            build/dvm-"$env:version"-windows-x64.sha256
          tag_name: "$env:version"
