name: Release to GitHub

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Create a GitHub release
        run: dart run grinder pkg-github-release
  upload-excutables-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-linux
      - name: Build checksums
        run: dart run grinder pkg-checksum-linux
      - name: Extract version
        run: echo "version=$(dart run grinder pkg-version)" >> $GITHUB_ENV
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-linux-ia32.sha256
            build/dvm-${{ env.version }}-linux-x64.sha256
            build/dvm-${{ env.version }}-linux-arm.sha256
            build/dvm-${{ env.version }}-linux-arm64.sha256
          tag_name: ${{ env.version }}
  upload-excutables-macos:
    needs: create-release
    strategy:
      matrix:
        args:
          [
            { image: macos-latest, arch: x64 },
            { image: macos-latest-xlarge, arch: arm64 },
          ]
    runs-on: ${{ matrix.args.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-macos-${{ matrix.args.arch }}
      - name: Build checksums
        run: dart run grinder pkg-checksum-macos-${{ matrix.args.arch }}
      - name: Extract version
        run: echo "version=$(dart run grinder pkg-version)" >> $GITHUB_ENV
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-macos-${{ matrix.args.arch }}.sha256
          tag_name: ${{ env.version }}
  upload-excutables-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-windows
      - name: Build checksums
        run: dart run grinder pkg-checksum-windows
      - name: Extract version
        run: |
          "version=$(dart run grinder pkg-version)" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-windows-ia32.sha256
            build/dvm-${{ env.version }}-windows-x64.sha256
          tag_name: ${{ env.version }}
  update-homebrew:
    needs:
      [
        create-release,
        upload-excutables-linux,
        upload-excutables-macos,
        upload-excutables-windows,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Extract version
        run: echo "version=$(dart run grinder pkg-version)" >> $GITHUB_ENV
      - name: Download checksums
        uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ env.version }}
          fileName: "*.sha256"
      - name: Extract checksums
        id: checksums
        shell: bash
        run: |
          echo "sha256_macos_x64=$(cat dvm-${{ env.version }}-macos-x64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "sha256_macos_arm64=$(cat dvm-${{ env.version }}-macos-arm64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "sha256_linux_x64=$(cat dvm-${{ env.version }}-linux-x64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_BLENDFACTORY_REPOSITORY_DISPATCHER }}
          private_key: ${{ secrets.PRIVATE_KEY_BLENDFACTORY_REPOSITORY_DISPATCHER }}
          owner: ${{ github.repository_owner }}
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: blendfactory/homebrew-tap
          event-type: update-dvm
          client-payload: |-
            {
              "version": "${{ env.version }}",
              "sha256_macos_x64": "${{ steps.checksums.outputs.sha256_macos_x64 }}",
              "sha256_macos_arm64": "${{ steps.checksums.outputs.sha256_macos_arm64 }}",
              "sha256_linux_x64": "${{ steps.checksums.outputs.sha256_linux_x64 }}",
            }
