name: Release to Github

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./github/actions/setup
      - name: Create a GitHub release
        run: dart run grinder pkg-github-release
  upload-excutables:
    needs: create-release
    strategy:
      matrix:
        args:
          [
            { image: ubuntu-latest, os: linux },
            { image: macos-latest, os: macos },
            { image: windows-latest, os: windows },
          ]
    runs-on: ${{ matrix.args.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-${{ matrix.args.os }}
