name: Release to GitHub

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Create a GitHub release
        run: dart run grinder pkg-github-release
  upload-excutables-linux:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-linux
      - name: Build checksums
        run: dart run grinder pkg-checksum-linux
      - name: Extract version
        run: echo "version=$(dart run grinder pkg-version)" >> $GITHUB_ENV
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-linux-ia32.sha256
            build/dvm-${{ env.version }}-linux-x64.sha256
            build/dvm-${{ env.version }}-linux-arm.sha256
            build/dvm-${{ env.version }}-linux-arm64.sha256
          tag_name: ${{ env.version }}
  upload-excutables-macos:
    needs: create-release
    strategy:
      matrix:
        args:
          [
            { image: macos-latest, arch: x64 },
            { image: macos-latest, arch: arm64 }, # macos-latest-xlarge is not available yet
          ]
    runs-on: ${{ matrix.args.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-macos-${{ matrix.args.arch }}
      - name: Build checksums
        run: dart run grinder pkg-checksum-macos-${{ matrix.args.arch }}
      - name: Extract version
        run: echo "version=$(dart run grinder pkg-version)" >> $GITHUB_ENV
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-macos-${{ matrix.args.arch }}.sha256
          tag_name: ${{ env.version }}
  upload-excutables-windows:
    needs: create-release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Upload excutables to GitHub
        run: dart run grinder pkg-github-windows
      - name: Build checksums
        run: dart run grinder pkg-checksum-windows
      - name: Extract version
        run: |
          "version=$(dart run grinder pkg-version)" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Upload checksums to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dvm-${{ env.version }}-windows-ia32.sha256
            build/dvm-${{ env.version }}-windows-x64.sha256
          tag_name: ${{ env.version }}
