name: Update Homebrew Formula

on:
  workflow_dispatch:

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Setup
        uses: ./.github/actions/setup
      - name: Extract DVM version
        id: extract-dvm-version
        uses: ./.github/actions/extract-dvm-version
      - name: Download checksums
        uses: robinraju/release-downloader@368754b9c6f47c345fcfbf42bcb577c2f0f5f395 # v1.9
        with:
          tag: ${{ steps.extract-dvm-version.outputs.version }}
          fileName: "*.sha256"
      - name: Extract checksums
        id: checksums
        shell: bash
        run: |
          echo "sha256_macos_x64=$(cat dvm-${{ steps.extract-dvm-version.outputs.version }}-macos-x64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "sha256_macos_arm64=$(cat dvm-${{ steps.extract-dvm-version.outputs.version }}-macos-arm64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "sha256_linux_x64=$(cat dvm-${{ steps.extract-dvm-version.outputs.version }}-linux-x64.sha256 | awk '{ print $1 }')" >> $GITHUB_OUTPUT
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@6c406e8a244fdf6bbf79e6cc8a91504a48d2c2ce # v1.9.2
        with:
          app-id: ${{ secrets.APP_ID_BLENDFACTORY_REPOSITORY_DISPATCHER }}
          private-key: ${{ secrets.PRIVATE_KEY_BLENDFACTORY_REPOSITORY_DISPATCHER }}
          owner: ${{ github.repository_owner }}
      - name: Dispatch repository event
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: blendfactory/homebrew-tap
          event-type: update-dvm
          client-payload: |-
            {
              "version": "${{ steps.extract-dvm-version.outputs.version }}",
              "sha256_macos_x64": "${{ steps.checksums.outputs.sha256_macos_x64 }}",
              "sha256_macos_arm64": "${{ steps.checksums.outputs.sha256_macos_arm64 }}",
              "sha256_linux_x64": "${{ steps.checksums.outputs.sha256_linux_x64 }}"
            }
